In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data = np.array([[3,7] ,
                [-4,-6] ,
                [1,-1] ,
                [7,8] ,
                [-4,-1] ,
                [-3,-7]])

In [ ]:
dataframe = pd.DataFrame(data , columns = ['x1', 'x2'])

In [ ]:
dataframe

x1  x2
0   3   7
1  -4  -6
2   1  -1
3   7   8
4  -4  -1
5  -3  -7

Step 1 : Convert the data in Standard Normal format

`Standard Normal format: If it contins mean as 0 and Standard deviation as 1`.

In [ ]:
dataframe.describe()

x1        x2
count  6.000000  6.000000
mean   0.000000  0.000000
std    4.472136  6.324555
min   -4.000000 -7.000000
25%   -3.750000 -4.750000
50%   -1.000000 -1.000000
75%    2.500000  5.000000
max    7.000000  8.000000

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
data_scaled = scaler.fit_transform(dataframe)

In [ ]:
dataframe = pd.DataFrame(data_scaled, columns = ['x1', 'x2'])

In [ ]:
dataframe.describe()

x1        x2
count  6.000000e+00  6.000000
mean   1.850372e-17  0.000000
std    1.095445e+00  1.095445
min   -9.797959e-01 -1.212436
25%   -9.185587e-01 -0.822724
50%   -2.449490e-01 -0.173205
75%    6.123724e-01  0.866025
max    1.714643e+00  1.385641

Now we compute covarience Matrix of two features x1 & x2 cov(x1 , x2)

In [ ]:
#Approach 1
c1 = dataframe.x1
c2 = dataframe.x2
np.cov(c1 , c2)

array([[1.2       , 1.06066017],
       [1.06066017, 1.2       ]])

In [ ]:
#Approach 2
covariancematrix = dataframe.T @ dataframe /5
covariancematrix

x1       x2
x1  1.20000  1.06066
x2  1.06066  1.20000

In [ ]:
eigenvalues, eigenvectors = np.linalg.eig(covariancematrix)

In [ ]:
## eagenvalues = fwatures
#eagenvalue represents the strength of the information given by the eagen vector
eigenvalues


array([2.26066017, 0.13933983])

In [ ]:
eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
eigenvectors[: , 0]

array([0.70710678, 0.70710678])

In [ ]:
dataframe

x1        x2
0  0.734847  1.212436
1 -0.979796 -1.039230
2  0.244949 -0.173205
3  1.714643  1.385641
4 -0.979796 -0.173205
5 -0.734847 -1.212436

In [ ]:
pc1 = dataframe @ eigenvectors[: , 0]

In [ ]:
pc1

0    1.376937
1   -1.427667
2    0.050731
3    2.192231
4   -0.815295
5   -1.376937
dtype: float64

In [ ]:
pc2 = dataframe @ eigenvectors[: , 1]
pc2

0    0.337706
1   -0.042027
2   -0.295680
3   -0.232640
4    0.570346
5   -0.337706
dtype: float64

Here first pc1 contains highest information given highest eigan values followed by pc2
- Pc2 contatins smaller information lesser than pc1